/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef, useMemo } from 'react';
import { applyProps } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';

const Lambo = props => {
  const lambo = useRef();
  const { scene, nodes, materials } = useGLTF('/lambo.glb');
  useMemo(() => {
    Object.values(nodes).forEach(
      node => node.isMesh && (node.receiveShadow = node.castShadow = true)
    );
    // applyProps(materials.headLightEmmissive1_mat, { emissive: true, emissiveIntensity: 10 })
    // applyProps(materials.headLightEmmissive2_mat, { emissive: true, emissiveIntensity: 10 })
    // applyProps(materials.tailLightEmmissive1_mat, { emissive: true, emissiveIntensity: 10 })
    applyProps(materials.wideBody_mat, {
      roughness: 0.5,
      metalness: 0.8,
      color: props.color,
      envMapIntensity: 2,
    });
    applyProps(materials.InsideBody_mat, {
      roughness: 0.5,
      metalness: 0.8,
      color: props.color,
      envMapIntensity: 2,
    });
    applyProps(materials.doorPart_mat, {
      roughness: 0.5,
      metalness: 0.8,
      color: props.color,
      envMapIntensity: 2,
    });
  }, [nodes, materials, props.color]);
  return <primitive ref={lambo} object={scene} {...props} />;
};

useGLTF.preload('/lambo.glb');

export default Lambo;

// const Lambo = ({ ...props }) => {
//   const group = useRef()
//   const { nodes, materials } = useGLTF('/lambo.glb')
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group position={[0, 0.77, 0]} rotation={[-Math.PI / 2, 0, 0]}>
//         <group rotation={[Math.PI / 2, 0, 0]}>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.carFloor_geom.geometry} material={materials.carFLoor_mat} />
//             <mesh geometry={nodes.insideBody_geom.geometry} material={materials.InsideBody_mat} />
//             <mesh geometry={nodes.sideSkirts_geom.geometry} material={materials.wideBody_mat} />
//             <mesh geometry={nodes.windowFrame_geom.geometry} material={materials.windowFrame_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.doorPart_geom.geometry} material={materials.doorPart_mat} />
//             <mesh geometry={nodes.doors_geom.geometry} material={materials.InsideBody_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.doorsBodyPart_geom.geometry} material={materials['Material.037']} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.doorWindowsSmallParts_geom.geometry} material={materials.widows_mat} />
//           </group>
//           <group position={[0, 0.91, 0]}>
//             <mesh geometry={nodes.exhaustInside_geom.geometry} material={materials.exhaustInside_mat} />
//             <mesh geometry={nodes.exhaustOutside_geom.geometry} material={materials.exhaustOutside_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.frontBumperInside_geom.geometry} material={materials.wideBody_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.frontBumper_geom.geometry} material={materials.InsideBody_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.FrontSkirt_geom.geometry} material={materials.wideBody_mat} />
//             <mesh geometry={nodes.FrontSkirtFlap_geom.geometry} material={materials.wideBodySkirtFlaps_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.frontTireRoof_geom.geometry} material={materials.wideBody_mat} />
//             <mesh geometry={nodes.frontTireRoofVinyl_geom.geometry} material={materials.windshieldVinyl_mat} />
//           </group>
//           <group position={[0, 0.01, -3.03]} rotation={[-2.83, 0, Math.PI / 2]} scale={0.16}>
//             <mesh geometry={nodes.frontWheelBrake_geom.geometry} material={materials.frontWheelBrake_mat} />
//             <mesh geometry={nodes.frontWheelBrakePart_geom.geometry} material={materials.frontWheelBrakePart_mat} />
//             <mesh geometry={nodes.frontWheelCenter_geom.geometry} material={materials.frontWheelDisk_mat} />
//             <mesh geometry={nodes.frontWheelDisk_geom.geometry} material={materials['frontWheelDisk_mat.001']} />
//             <mesh geometry={nodes.frontWheelEmblem_geom.geometry} material={materials.frontWheelEmblem_mat} />
//             <mesh geometry={nodes.frontWheelEmblemHolder_geom.geometry} material={materials.frontWheelEmblemHolder_mat} />
//             <mesh geometry={nodes.frontWheelMetalParts_geom.geometry} material={materials.CRBN_JANTE} />
//             <mesh geometry={nodes.frontWheelNuts_geom.geometry} material={materials.frontWheelNuts_mat} />
//             <mesh geometry={nodes.frontWheelRims_geom.geometry} material={materials['Material.013']} />
//             <mesh geometry={nodes.frontWheelRubber_geom.geometry} material={materials.frontWheelRubber_mat} />
//             <mesh geometry={nodes.frontWheelRubberDet_geom.geometry} material={materials.frontWheelRubber_mat} />
//             <mesh geometry={nodes.frontWheelRubberWhite_geom.geometry} material={materials.frontWheelRubberWhite_mat} />
//             <mesh geometry={nodes.frontWheelTextLogo_geom.geometry} material={materials.Chrome_Text_Logo} />
//           </group>
//           <group position={[0, 0.01, 0]} rotation={[-2.83, 0, Math.PI / 2]} scale={0.16}>
//             <mesh geometry={nodes.frontWheelBrake_geom001.geometry} material={materials.frontWheelBrake_mat} />
//             <mesh geometry={nodes.frontWheelBrakePart_geom001.geometry} material={materials.frontWheelBrakePart_mat} />
//             <mesh geometry={nodes.frontWheelCenter_geom001.geometry} material={materials.frontWheelDisk_mat} />
//             <mesh geometry={nodes.frontWheelDisk_geom001.geometry} material={materials['frontWheelDisk_mat.001']} />
//             <mesh geometry={nodes.frontWheelEmblem_geom001.geometry} material={materials.frontWheelEmblem_mat} />
//             <mesh geometry={nodes.frontWheelEmblemHolder_geom001.geometry} material={materials.frontWheelEmblemHolder_mat} />
//             <mesh geometry={nodes.frontWheelMetalParts_geom001.geometry} material={materials.CRBN_JANTE} />
//             <mesh geometry={nodes.frontWheelNuts_geom001.geometry} material={materials.frontWheelNuts_mat} />
//             <mesh geometry={nodes.frontWheelRims_geom001.geometry} material={materials['Material.013']} />
//             <mesh geometry={nodes.frontWheelRubber_geom001.geometry} material={materials.frontWheelRubber_mat} />
//             <mesh geometry={nodes.frontWheelRubberDet_geom001.geometry} material={materials.frontWheelRubber_mat} />
//             <mesh geometry={nodes.frontWheelRubberWhite_geom001.geometry} material={materials.frontWheelRubberWhite_mat} />
//             <mesh geometry={nodes.frontWheelTextLogo_geom001.geometry} material={materials.Chrome_Text_Logo} />
//           </group>
//           <group scale={[1, 0.1, 1]}>
//             <mesh geometry={nodes.frontWheelsExhaustFlaps_geom.geometry} material={materials.frontWheelsExhaustFlaps_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.hood_geom.geometry} material={materials.wideBody_mat} />
//           </group>
//           <group position={[-4.01, 0, -0.08]} scale={0.03}>
//             <group rotation={[0, 0, Math.PI / 2]} scale={0.1}>
//               <group position={[-297.24, -1575.53, -648.24]} rotation={[Math.PI / 2, 0, 0]} scale={69.7}>
//                 <mesh geometry={nodes.Object_8.geometry} material={materials['Material.017']} />
//               </group>
//               <group position={[-192.22, -1579.68, 30]} rotation={[Math.PI / 2, 0, 0]} scale={48.67}>
//                 <mesh geometry={nodes.Object_6.geometry} material={materials['Material.017']} />
//               </group>
//             </group>
//           </group>
//           <group position={[0, -0.48, -0.57]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.63}>
//             <mesh geometry={nodes.headLightEmissive1_geom.geometry} material={materials.headLightEmissive1_mat} />
//             <mesh geometry={nodes.headLightHolder_geom.geometry} material={materials.headLightHolder_mat} />
//             <mesh geometry={nodes.headLightInside_geom.geometry} material={materials.black} />
//             <mesh geometry={nodes.headLightInsideFrame_geom.geometry} material={materials.headLightInsideFrame_mat} />
//             <mesh geometry={nodes.headLightLens_geom.geometry} material={materials.headLightLens_mat} />
//             <mesh geometry={nodes.headLightLensEmissive2_geom.geometry} material={materials.headLightLensEmissive2_mat} />
//             <mesh geometry={nodes.tailLightBelow_geom.geometry} material={materials.tailLightBelow_mat} />
//             <mesh geometry={nodes.tailLightBody_geom.geometry} material={materials.tailLightBody_mat} />
//             <mesh geometry={nodes.tailLightEmissive1_geom.geometry} material={materials.tailLightEmissive1_mat} />
//           </group>
//           <group position={[0, 0.09, 1.2]} scale={[0.56, 1, 1]}>
//             <mesh geometry={nodes.Object_104.geometry} material={materials['Material.011']} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.rearExhaustBelowPanel_mat.geometry} material={materials.wideBody_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.rearExhaustCover_geom.geometry} material={materials.rearWindshield_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.rearLightsUnderPanel_geom.geometry} material={materials.InsideBody_mat} />
//             <mesh geometry={nodes.rearLightsUnderPanelWidebody_geom.geometry} material={materials.wideBody_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.rearSpoiler_geom.geometry} material={materials.rearWindshield_mat} />
//             <mesh geometry={nodes.rearSpoilerRedPart_geom.geometry} material={materials['Material.008']} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.RearWheelWideBody_geom.geometry} material={materials.wideBody_mat} />
//             <mesh geometry={nodes.rearWheelWideBodyVinyl_geom.geometry} material={materials.wideBodySkirtFlaps_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.rearWideBodyFlap_geom.geometry} material={materials.wideBodySkirtFlaps_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.partBetween_geom.geometry} material={materials['Material.008']} />
//             <mesh geometry={nodes.rearWideBodyPart_geom.geometry} material={materials.rearWindshield_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.rearWideBodyPartSide_geom.geometry} material={materials.rearWindshield_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.rearWindowShield_geom.geometry} material={materials.rearWindowShield_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.rearWindshield_geom.geometry} material={materials.rearWindshield_mat} />
//             <mesh geometry={nodes.rearWindshieldAccent_mat.geometry} material={materials.wideBodySkirtFlaps_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.sideMirrorBody_geom.geometry} material={materials.wideBody_mat} />
//             <mesh geometry={nodes.sideMirrorBodyAccent_geom.geometry} material={materials.wideBodySkirtFlaps_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.sideMirrorsShiny_mat.geometry} material={materials.sideMirrorsShiny_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.tailLightAbovePart_geom.geometry} material={materials.wideBody_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.tailLightBelowCover_geom.geometry} material={materials.rearWindshield_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.wideBodySkirtFlaps_geom.geometry} material={materials.wideBodySkirtFlaps_mat} />
//           </group>
//           <group rotation={[Math.PI / 2, 0, 0]}>
//             <mesh geometry={nodes.windows_geom.geometry} material={materials.widows_mat} />
//             <mesh geometry={nodes.windshieldVinyl_geom.geometry} material={materials.windshieldVinyl_mat} />
//           </group>
//         </group>
//       </group>
//     </group>
//   )
// }
